
[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"

[window.padding]
x = 12
y = 12

# [window]
# padding = { x = 12, y = 12 }

[general]
### themes from https://github.com/alacritty/alacritty-theme.git
import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[scrolling]
multiplier = 10
